name: Own-Actions-wf
on: push
jobs:
  testing-action:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: ./actions/issue
        id: issue
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          title: Title
          body: Body
          assignees: |
            NidhiPatel-20 
            alialaa
      - run: |
          echo ${{ steps.issue.outputs.issue }}
          chmod +x ./.github/actions/hello-docker/entrypoint.sh 
      - uses: ./.github/actions/hello-docker
        id: hello
        with:
          who-to-greet: "WORLD..!!"
      - run: |
          echo "Time: ${{ steps.hello.outputs.time }}"
          echo $HELLO

