name: Own-Actions-wf
on: push
jobs:
  testing-action:
    runs-on: ubuntu-latest
    steps:
      # - uses: actions/checkout@v2
      # - name: Sending slack message
      #   uses: ./.github/actions/slack
      #   with:
      #     slack_webhook: ${{ secrets.SLACK_WEBHOOK }}
      #     message: Hello Slack
      - uses: SnehaDavari/open-issue@v1.0.0
        id: issue
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          title: Title
          body: Body
          assignees: |
            NidhiPatel-20 
             
      - run: |
          echo ${{ steps.issue.outputs.issue }}
          chmod +x ./.github/actions/hello-docker/entrypoint.sh 
      - uses: ./.github/actions/hello-docker
        id: hello
        with:
          who-to-greet: "WORLD..!!"
      - run: |
          echo "Time: ${{ steps.hello.outputs.time }}"
          echo $HELLO

