name: CI
on:
  pull_request:
    branches: [develop]

jobs:
  build:
      runs-on: ubuntu-latest
      steps: 
        - uses: actions/checkout@v1
        - name: Use NodeJS cmds
          uses: actions/setup-node@v1 
          with: 
            node-version: "15.x"
        - run: npm ci
        - run: npm run format:check
        - run: npm test -- --coverage
          env: 
            CI: true
        - name: Echo string
          run: echo "Hi Nidhi.."
        - name: run commands
          run: pwd
        
