name: CI-Workflow
on: push

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Use Nodejs
        uses: actions/setup-node@v1
        with:
          node-version: "15.x"
      - run: npm ci
      - run: npm run format-check
      - run: npm run format
      - run: npm test -- --coverage
        env:
          CI: true
      - name: Upload Test Coverage
        uses: actions/upload-artifact@v1
        with:
          name: code-coverage
          path: coverage
      - name: Build project
        if: github.event_name == 'push'
        run: npm run build
      - name: Upload build folder
        uses: actions/upload-artifact@v1
        with:
          name: build
          path: build
      - name: Deploy to stating
        if: github.event_name == 'push'
        run: npx surge --project ./build --domain somber-foot.surge.sh
        env:
          SURGE_LOGIN: ${{ secrets.SURGE_LOGIN }}
          SURGE_TOKEN: ${{ secrets.SURGE_TOKEN }}
